// <auto-generated />
using System;
using EventosArtisticos_Manuel.api.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventosArtisticos_Manuel.api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220112185940_Venta")]
    partial class Venta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("IdServicios")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdServicios");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Servicios", b =>
                {
                    b.Property<int>("IdServicios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdServicios");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasMaxLength(120)
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionServicio")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Monto")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Cliente", b =>
                {
                    b.HasOne("EventosArtisticos_Manuel.api.Modelos.Servicios", "Servicios")
                        .WithMany("Cliente")
                        .HasForeignKey("IdServicios");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Servicios", b =>
                {
                    b.HasOne("EventosArtisticos_Manuel.api.Modelos.Categoria", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("IdCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Venta", b =>
                {
                    b.HasOne("EventosArtisticos_Manuel.api.Modelos.Cliente", "Cliente")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Categoria", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("EventosArtisticos_Manuel.api.Modelos.Servicios", b =>
                {
                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
